### ISSUE TITLE
hexo deploy : 未配置git global账号

### ISSUE THREAD

**Issue by huliangfei** [huliangfei/huliangfei.github.io#3]
[root@manage01 hexo-blog]# hexo deploy
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in /data/hexo-blog/.deploy_git/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@manage01.(none)')
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@manage01.(none)')

    at ChildProcess.<anonymous> (/data/hexo-blog/node_modules/hexo-util/lib/spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

**Comment by huliangfei** [comment]
这个错误是因为当前本地的Git还没配置用户信息, 所以执行以下命令:

$ git config --global user.email "xiaoming@163.com"

$ git config --global user.name "xiaoming"

$ hexo d
此时,会要求输入用户名, 你就输入你的用户名: xiaoming
接着要求输入密码, 你就入密码. 密码输入期间不会看到任何字符.然后直接回车即可.

作者：alamu
链接：http://www.jianshu.com/p/21d80d5bfca1
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
